spring.application.name=web
server.port =8082

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0100276540Krams
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Print the actual SQL queries being executed to the console
spring.jpa.show-sql=true

# Format the printed SQL so it's easy to read
spring.jpa.properties.hibernate.format_sql=true

# Show the actual values being bound to parameters
logging.level.org.hibernate.orm.jdbc.bind=trace