spring.config.import=optional:file:.env[.properties]
spring.application.name=web
server.port =8082

#JWT SECRETS AND EXPIRATION KEY VARIABLES
jwt.secret = ${JWT_SECRET}
jwt.expiration =${JWT_EXPIRATION}

# MPESA PAYMENT INTEGRATION VARIABLES
consumer.key = ${CONSUMER_KEY}
consumer.secret = ${CONSUMER_SECRET}
bs.shortcode= ${BUSINESS_SHORTCODE}

# DATABASE CONFIG VARIABLES
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_USERNAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Print the actual SQL queries being executed to the console
spring.jpa.show-sql=true

# Format the printed SQL so it's easy to read
spring.jpa.properties.hibernate.format_sql=true

# Show the actual values being bound to parameters
logging.level.org.hibernate.orm.jdbc.bind=trace